<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Live auction bids:
 * - kind: 'sealed' = the supplier's sealed quote carried in as their opening position,
 *         'live'   = a bid placed during the auction.
 * - idempotency_key: generated by the browser per bid attempt, so a double-tap or a network
 *   retry is recorded once.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('bids', function (Blueprint $table) {
            $table->string('kind', 10)->default('live')->after('rfq_item_id');
            $table->string('idempotency_key', 64)->nullable()->after('kind');
            $table->unique(['auction_id', 'supplier_org_id', 'idempotency_key'], 'bids_idempotency_unique');
        });

        Schema::table('auctions', function (Blueprint $table) {
            $table->foreignId('created_by')->nullable()->after('organization_id')->constrained('users')->nullOnDelete();
            $table->string('cancel_reason')->nullable()->after('closed_at');
        });
    }

    public function down(): void
    {
        Schema::table('auctions', function (Blueprint $table) {
            $table->dropConstrainedForeignId('created_by');
            $table->dropColumn('cancel_reason');
        });

        Schema::table('bids', function (Blueprint $table) {
            $table->dropUnique('bids_idempotency_unique');
            $table->dropColumn(['kind', 'idempotency_key']);
        });
    }
};
